-- Insert 10 random notes with markdown content
INSERT INTO notes (id, title, note, archive, favorite, created_at, modified_at)
VALUES
  ('n_a7f3d9e1', 'Project Brainstorming', '# Project Ideas for Q2\n\nAfter our team meeting last week, I''ve been thinking about potential directions for our next sprint. The **customer feedback** highlighted several pain points we could address:\n\n- Improving the dashboard loading time\n- Adding export functionality to reports\n- Creating a more intuitive onboarding flow\n\nI think the onboarding flow should be our priority since it directly impacts user retention.', false, true, NOW() - INTERVAL '30 days', NOW() - INTERVAL '25 days'),
  
  ('n_b8e2c5d7', 'Meeting Notes: Client Presentation', 'Yesterday''s client presentation went surprisingly well. The team did an **excellent job** addressing concerns about the timeline. Some key takeaways:\n\n1. The client wants weekly progress reports instead of bi-weekly\n2. They''ve agreed to the proposed budget increase for Phase 2\n3. The deadline extension was approved, giving us an extra two weeks\n\nWe need to schedule a follow-up call next Monday to discuss implementation details.', false, false, NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
  
  ('n_c4f9a2b3', 'Book Recommendations', '## Books I Want to Read\n\nI''ve been collecting recommendations for my summer reading list. These came highly recommended by colleagues:\n\n- *The Psychology of Money* by Morgan Housel\n- *Atomic Habits* by James Clear\n- *Deep Work* by Cal Newport\n\nI started *Deep Work* last night and I''m already finding the focused concentration techniques applicable to my daily workflow. The concept of **depth vs. shallow** work is particularly relevant.', false, true, NOW() - INTERVAL '45 days', NOW() - INTERVAL '10 days'),
  
  ('n_d2e7f8a5', 'Recipe: Sourdough Bread', '# Sourdough Bread Recipe\n\nFinally perfected my sourdough technique after months of practice!\n\n## Ingredients\n- 500g bread flour\n- 350g water\n- 100g active sourdough starter\n- 10g salt\n\n## Process\n1. Mix flour and water, rest for 30 minutes\n2. Add starter and salt, fold every 30 minutes for 2-3 hours\n3. Shape and cold proof overnight\n4. Bake at 450°F in a dutch oven\n\nThe key was increasing the **hydration level** and the longer cold proof in the refrigerator.', false, false, NOW() - INTERVAL '60 days', NOW() - INTERVAL '60 days'),
  
  ('n_e5d1c9b6', 'Vacation Planning', 'Starting to plan our trip to Portugal for next spring. The current itinerary looks like:\n\n- 3 nights in Lisbon\n- 2 nights in Sintra\n- 4 nights in Porto\n- 3 nights in the Algarve\n\nStill need to research accommodations in Porto. Several people recommended staying near the **Ribeira district** for the best experience. Also need to look into wine tours in the Douro Valley, which apparently is an absolute must-do from Porto.', true, false, NOW() - INTERVAL '90 days', NOW() - INTERVAL '85 days'),
  
  ('n_f3b8a7c2', 'Learning Path: Machine Learning', '## My ML Learning Roadmap\n\nI''ve mapped out a structured approach to finally learn machine learning this year:\n\n1. Brush up on Python and statistics fundamentals (2 weeks)\n2. Complete the Stanford Machine Learning course (6 weeks)\n3. Work through the book *Hands-On Machine Learning with Scikit-Learn* (8 weeks)\n4. Build 3 projects to apply the concepts (12 weeks):\n   - Predictive maintenance model for work\n   - Image classification project\n   - NLP sentiment analysis\n\nThe key is **consistent practice** rather than rushing through the material.', false, true, NOW() - INTERVAL '10 days', NOW() - INTERVAL '5 days'),
  
  ('n_g1h2i3j4', 'Home Renovation Ideas', 'After talking with the contractor yesterday, we have some decisions to make about the kitchen remodel:\n\n- Countertops: leaning toward quartz (more durable than marble)\n- Cabinets: white upper cabinets with navy blue lowers would create a nice contrast\n- Flooring: the wide-plank engineered hardwood looks beautiful and is within budget\n- Backsplash: simple white subway tile with dark grout\n\nThe **open shelving** concept is appealing, but I''m concerned about dust and having to keep everything perfectly organized.', false, false, NOW() - INTERVAL '7 days', NOW() - INTERVAL '2 days'),
  
  ('n_h9i8j7k6', 'Weekly Reflection', '### Week in Review\n\nThis was a productive week despite the challenges:\n\n- Completed the database migration with minimal downtime\n- Onboarded two new team members\n- Finalized the Q3 roadmap document\n\nI''m still struggling with **context switching** between management tasks and technical work. Need to block out focused time on my calendar for deep work sessions. Tomorrow I''ll try the Pomodoro technique again to see if that helps with maintaining focus.', true, false, NOW() - INTERVAL '120 days', NOW() - INTERVAL '120 days'),
  
  ('n_i6j5k4l3', 'Health Goals', 'My wellness plan for the next three months:\n\n1. **Exercise**: 30 minutes of activity 5 days per week\n   - Monday/Wednesday/Friday: Strength training\n   - Tuesday/Thursday: Cardio or yoga\n   
2. **Nutrition**:\n   - Meal prep on Sundays\n   - Increase protein intake\n   - Reduce processed foods\n   
3. **Sleep**:\n   - Consistent 10:30pm bedtime\n   - No screens 1 hour before bed\n\nTracking my progress in a journal has been helpful for accountability. I''ve noticed significant improvements in energy levels since implementing the consistent sleep schedule.', false, true, NOW() - INTERVAL '15 days', NOW() - INTERVAL '3 days'),
  
  ('n_j2k1l9m8', 'Photography Tips', '## Improving Landscape Photography\n\nLessons from yesterday''s photography workshop:\n\n1. The **golden hour** (just after sunrise or before sunset) provides the most flattering light for landscapes\n2. Use a small aperture (f/11 to f/16) for greater depth of field\n3. A polarizing filter can reduce glare and enhance colors, especially useful for water and sky\n4. Consider foreground elements to create depth in the composition\n5. Shoot in RAW format for maximum flexibility in post-processing\n\nNext weekend I''ll practice these techniques at the state park.', false, false, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days');